### ISSUE TITLE
npm run problem

### ISSUE THREAD

**Issue by gopeine** [versx/PoGoEventWatcher#13]
Hey hi the command npm run create-locales didnt work... npm always says create-locales is missing....

**Comment by versx** [comment]
> Hey hi the command npm run create-locales didnt work... npm always says create-locales is missing....

Did you update to latest? I fixed it 1-2 commits ago.

**Comment by gopeine** [comment]
oh wtf, i thinked freshed cloned from github should be latest... but it wasnt... nvm now it worked thx
