### ISSUE TITLE
"deletePreviousEvents" does not work for Auto post.

### ISSUE THREAD

**Issue by Ou71and3r** [versx/PoGoEventWatcher#15]
"deletePreviousEvents" does not work for Auto post.

Example: EventWatcher auto post the list with events and and immediately after that delete all of them, not only the old posts. 

The only workaround for this is to disable "deletePreviousEvents", but then all posts remain and the channel get flooded with old posts.

**Comment by versx** [comment]
Should be fixed in https://github.com/versx/PoGoEventWatcher/releases/tag/2.0.5
